Sprint 1
SupergroverNN/middle.messenger.praktikum.yandex pull request #1
Opened 2021-03-30 16:12 UTC by SupergroverNN

2021-03-31 19:55 UTC, Goreliy92 commented on package.json
> +{
Укажи пожалуйста  версию NodeJS в .nvmrc или engine в package.json. Она должна быть не ниже 12;

2021-03-31 19:56 UTC, Goreliy92 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
Удаляй не нужные скрипты

2021-03-31 19:57 UTC, Goreliy92 commented on static/html/index.html
> +<script></script>
Нужно удалять лишнее

2021-03-31 20:02 UTC, Goreliy92 commented on static/styles/auth.scss
> +  background-color: #ffffff;
Для цветов лучше использовать переменный
И не только для цветов, старайся выносить в переменные часто используемые значения
отступы, цвета и так далее

2021-03-31 20:03 UTC, Goreliy92 commented on static/templates/404.pug
> +doctype html
дублируется doctype

2021-03-31 20:05 UTC, Goreliy92 commented on static/templates/404.pug
> +doctype html
Нужно было сделать: 
**Все страницы сделаны на шаблонах и вставляются в DOM с использованием шаблонизатора.**
Сейчас просто весь html лежит в темплейтах и мы его транспайлим в html. Нужно все разделить
С помощью pug рендерить только динамические данные, статические данные должны лежать в html

2021-03-31 20:06 UTC, Goreliy92 commented on static/templates/chats.pug
> +  const searchBlock = document.querySelector('.chat_list--search');
js должен лежать отдельно и подключаться в html файлах
Нужно разбить все на модули , html pug js

2021-03-31 20:08 UTC, Goreliy92 commented on static/templates/registration.pug
> +  const form = document.querySelector('.reg_form');
давай сделаем отдельный модуль для сбора данных форм. Правильней использовать FormData. 
Событие правильней добавлять через addEventListener

2021-03-31 20:12 UTC, Goreliy92 requested changes
Привет, спасибо за работу. 
Нужно еще немного доработать:
1. Удалить все не нужное : дублированные тэги, пустые тэги, пустые файлы
2. Больше использовать общих стилей
3. Разбить все на модули. 
Посмотри внимательно на комментарии. 
Я думаю ты быстро все поправишь. Удачи

2021-04-01 08:09 UTC, SupergroverNN commented on package.json
> +{
блин, после переноса проекта в новую репу не перенесся файл .nvmrc. 
fixed

2021-04-01 08:09 UTC, SupergroverNN commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
fixed

2021-04-01 09:13 UTC, SupergroverNN commented on static/styles/auth.scss
> +  background-color: #ffffff;
вынес основные цвета в переменные и один из типов текста в миксин

2021-04-01 09:14 UTC, SupergroverNN commented on static/templates/404.pug
> +doctype html
fixed

2021-04-01 09:18 UTC, SupergroverNN commented on static/templates/404.pug
> +doctype html
не совсем понял, что в контексте макета является динамическими и статическими данными?
каркас html с одним дивом внутри и айди на которые прикрепится потом содержимое шаблона (со всем остальным) будет считаться верным решением?

2021-04-01 10:37 UTC, Goreliy92 commented on static/templates/404.pug
> +doctype html
Да, так будет правильнее

2021-04-01 14:32 UTC, SupergroverNN commented on static/templates/registration.pug
> +  const form = document.querySelector('.reg_form');
fixed

2021-04-01 14:47 UTC, SupergroverNN commented on static/templates/chats.pug
> +  const searchBlock = document.querySelector('.chat_list--search');
все поломалось после разбиения на модули, точнее каждая отдельная страница работает но вместе нет (

2021-04-01 16:10 UTC, SupergroverNN commented on static/templates/chats.pug
> +  const searchBlock = document.querySelector('.chat_list--search');
теперь у меня есть структура page.html + page.js + page.pug, при работе с одной страницей через скрипт "dev": "parcel static/html/index.html" все работает

но при работе со скриптом "build": "parcel build static/html/*.html", где по идее должны склеиться из html+js+pug полноценный html, генерятся страница отдельно пустой html и отдельно pug контект.. осталось просто сбилдить это кучно

2021-04-02 16:24 UTC, SupergroverNN commented on static/html/index.html
> +<script></script>
fixed

2021-04-02 16:24 UTC, SupergroverNN commented on static/templates/404.pug
> +doctype html
fixed

2021-04-02 16:24 UTC, SupergroverNN commented on static/templates/chats.pug
> +  const searchBlock = document.querySelector('.chat_list--search');
fixed

2021-04-02 16:25 UTC, SupergroverNN commented
Поправил указанные недочеты.

2021-04-03 12:19 UTC, Goreliy92 commented on static/js/profile.js
> +
пустой файл

2021-04-03 12:20 UTC, Goreliy92 commented on static/js/registration.js
> +    const inputs = form.querySelectorAll('input');
Все данные инпутов уже должны лежать в FormData

2021-04-03 12:24 UTC, Goreliy92 commented
Привет. Спасибо что поправил! Работа очень аккуратная!
Зачет. Удачи в следующем спринте

2021-04-21 16:45 UTC, closed without merging